name: ${project.name}
main: ${project.groupId}.BadgePlugin
version: ${project.version}
authors: [ Wertik1206 ]
commands:
  badgerbadges:
    aliases: [ bb, badge, badges, badgerbadge ]

permissions:
  badgerbadges.view.others:
    description: View badges of other players.